[package]
name = "Actual_Test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.4"
egui = "0.22.0"
epi = "0.15.0"
eframe = "0.15.0"
rand = "0.8.4"
chrono = "0.4.19"